version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - .prod.env
    ports:
      - 3307:3306
    volumes:
      - db_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.5
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_volume:/data
  
  app:
    image: sophiehsu/auth-api:1.2.1
    environment:
      - ENV=production
    env_file:
      - .prod.env
    ports:
      - 8000:8000
    volumes:
      - ./logs_prod:/app/logs
    depends_on:
      - db
      - redis

volumes:
  db_volume:
  redis_volume:

networks:
  default:
    name: auth_system_network

