version: '3.8'

services:
  app:
    build: .
    environment:
      - ENV=production
    env_file:
      - .prod.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


  db:
    image: mysql:8.0
    env_file:
      - .db.env
    ports:
      - 3307:3306
    volumes:
      - ./volumes/db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.5
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./volumes/redis_data:/data


networks:
  default:
    name: auth_system_network

