name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        DATABASE_URL: "mysql+mysqlconnector://testuser:123$@localhost/auth"  
        REDIS_URL: "redis://localhost:6379/0"  
        USE_MOCK_DB: "True"  
        USE_MOCK_REDIS: "True"
      run: |
        # Export environment variables to use Mock configurations
        export USE_MOCK_DB=True
        export USE_MOCK_REDIS=True

        mkdir -p reports
        pytest --junitxml=reports/results.xml

    - name: Publish Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports/results.xml