name: Python application

on:
  push:
    branches: 
      - '**'
jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: auth
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Set environment variables
      run: |
        echo "DATABASE_URL=mysql+pymysql://root:root_password@localhost:3306/auth" >> $GITHUB_ENV
    
    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h"localhost" --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Run tests
      run: |
        pytest --junitxml=reports/results.xml 

    - name: Publish Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports/results.xml
